---
- name: service - ensure apache is running
  service: name=apache2 state=started enabled=yes
  when: passenger_webserver == "apache"

- name: service - ensure nginx is running
  service: name=nginx state=started enabled=yes
  when: passenger_webserver == "nginx"
